import {DependencyContainer} from 'tsyringe';
import {IPreSptLoadMod} from '@spt/models/external/IPreSptLoadMod';
import {IPostDBLoadMod} from '@spt/models/external/IPostDBLoadMod';
import {IPostSptLoadMod} from '@spt/models/external/IPostSptLoadMod';
import {ILogger} from "@spt/models/spt/utils/ILogger";
import {DatabaseServer} from '@spt/servers/DatabaseServer';
import {IDatabaseTables} from '@spt/models/spt/server/IDatabaseTables';
import {ItemHelper} from '@spt/helpers/ItemHelper';
import {CustomItemService} from '@spt/services/mod/CustomItemService';
import addExtendMagazine_9A91 from './modifies/addExtendMagazine_9A91';
import addExtendMagazine_ADAR from './modifies/addExtendMagazine_ADAR';
import addExtendMagazine_AVT40 from './modifies/addExtendMagazine_AVT40';
import addExtendMagazine_OPSKS from './modifies/addExtendMagazine_OPSKS';
import addExtendMagazine_RFB from './modifies/addExtendMagazine_RFB';
import addExtendMagazine_SAGAK545 from './modifies/addExtendMagazine_SAGAK545';
import addExtendMagazine_SAGAK545S from './modifies/addExtendMagazine_SAGAK545S';
import addExtendMagazine_SKS from './modifies/addExtendMagazine_SKS';
import addExtendMagazine_SR3M from './modifies/addExtendMagazine_SR3M';
import addExtendMagazine_SVT40 from './modifies/addExtendMagazine_SVT40';
import addExtendMagazine_TX15 from './modifies/addExtendMagazine_TX15';
import addExtendMagazine_VPO101 from './modifies/addExtendMagazine_VPO101';
import addExtendMagazine_VPO136 from './modifies/addExtendMagazine_VPO136';
import addExtendMagazine_VPO209 from './modifies/addExtendMagazine_VPO209';
import addExtendMagazine_VSK94 from './modifies/addExtendMagazine_VSK94';
import addExtendMagazine_AK12 from './modifies/addExtendMagazine_AK12';
import addExtendMagazine_AK74 from './modifies/addExtendMagazine_AK74';
import addExtendMagazine_AK74M from './modifies/addExtendMagazine_AK74M';
import addExtendMagazine_AK74N from './modifies/addExtendMagazine_AK74N';
import addExtendMagazine_AK101 from './modifies/addExtendMagazine_AK101';
import addExtendMagazine_AK102 from './modifies/addExtendMagazine_AK102';
import addExtendMagazine_AK103 from './modifies/addExtendMagazine_AK103';
import addExtendMagazine_AK104 from './modifies/addExtendMagazine_AK104';
import addExtendMagazine_AK105 from './modifies/addExtendMagazine_AK105';
import addExtendMagazine_AKM from './modifies/addExtendMagazine_AKM';
import addExtendMagazine_AKMN from './modifies/addExtendMagazine_AKMN';
import addExtendMagazine_AKMS from './modifies/addExtendMagazine_AKMS';
import addExtendMagazine_AKMSN from './modifies/addExtendMagazine_AKMSN';
import addExtendMagazine_AKS74 from './modifies/addExtendMagazine_AKS74';
import addExtendMagazine_AKS74N from './modifies/addExtendMagazine_AKS74N';
import addExtendMagazine_AKS74U from './modifies/addExtendMagazine_AKS74U';
import addExtendMagazine_AKS74UB from './modifies/addExtendMagazine_AKS74UB';
import addExtendMagazine_AKS74UN from './modifies/addExtendMagazine_AKS74UN';
import addExtendMagazine_ASVAL from './modifies/addExtendMagazine_ASVAL';
import addExtendMagazine_ASH12 from './modifies/addExtendMagazine_ASH12';
import addExtendMagazine_AUGA1 from './modifies/addExtendMagazine_AUGA1';
import addExtendMagazine_AUGA3 from './modifies/addExtendMagazine_AUGA3';
import addExtendMagazine_AUGA3B from './modifies/addExtendMagazine_AUGA3B';
import addExtendMagazine_MDR556 from './modifies/addExtendMagazine_MDR556';
import addExtendMagazine_MDR762 from './modifies/addExtendMagazine_MDR762';
import addExtendMagazine_G36 from './modifies/addExtendMagazine_G36';
import addExtendMagazine_416A5 from './modifies/addExtendMagazine_416A5';
import addExtendMagazine_M4A1 from './modifies/addExtendMagazine_M4A1';
import addExtendMagazine_MCX from './modifies/addExtendMagazine_MCX';
import addExtendMagazine_MCXSPEAR from './modifies/addExtendMagazine_MCXSPEAR';
import addExtendMagazine_MK47 from './modifies/addExtendMagazine_MK47';
import addExtendMagazine_RD704 from './modifies/addExtendMagazine_RD704';
import addExtendMagazine_SA58 from './modifies/addExtendMagazine_SA58';
import addExtendMagazine_SCARH from './modifies/addExtendMagazine_SCARH';
import addExtendMagazine_SCARHF from './modifies/addExtendMagazine_SCARHF';
import addExtendMagazine_SCARL from './modifies/addExtendMagazine_SCARL';
import addExtendMagazine_SCARLF from './modifies/addExtendMagazine_SCARLF';
import addExtendMagazine_Velociraptor from './modifies/addExtendMagazine_Velociraptor';
import addExtendMagazine_AXMC from './modifies/addExtendMagazine_AXMC';
import addExtendMagazine_DVL10 from './modifies/addExtendMagazine_DVL10';
import addExtendMagazine_M700 from './modifies/addExtendMagazine_M700';
import addExtendMagazine_MosinSniper from './modifies/addExtendMagazine_MosinSniper';
import addExtendMagazine_MosinInfantry from './modifies/addExtendMagazine_MosinInfantry';
import addExtendMagazine_SV98 from './modifies/addExtendMagazine_SV98';
import addExtendMagazine_T5000M from './modifies/addExtendMagazine_T5000M';
import addExtendMagazine_TRGM10 from './modifies/addExtendMagazine_TRGM10';
import addExtendMagazine_VPO215 from './modifies/addExtendMagazine_VPO215';
import addExtendMagazine_AK50 from './modifies/addExtendMagazine_AK50';
import addExtendMagazine_G28 from './modifies/addExtendMagazine_G28';
import addExtendMagazine_M1A from './modifies/addExtendMagazine_M1A';
import addExtendMagazine_MK18 from './modifies/addExtendMagazine_MK18';
import addExtendMagazine_RSASS from './modifies/addExtendMagazine_RSASS';
import addExtendMagazine_SR25 from './modifies/addExtendMagazine_SR25';
import addExtendMagazine_SVDS from './modifies/addExtendMagazine_SVDS';
import addExtendMagazine_VSS from './modifies/addExtendMagazine_VSS';
import addExtendMagazine_M60E4 from './modifies/addExtendMagazine_M60E4';
import addExtendMagazine_M60E6 from './modifies/addExtendMagazine_M60E6';
import addExtendMagazine_M60E6F from './modifies/addExtendMagazine_M60E6F';
import addExtendMagazine_PKM from './modifies/addExtendMagazine_PKM';
import addExtendMagazine_PKP from './modifies/addExtendMagazine_PKP';
import addExtendMagazine_RPD from './modifies/addExtendMagazine_RPD';
import addExtendMagazine_RPDN from './modifies/addExtendMagazine_RPDN';
import addExtendMagazine_RPK16 from './modifies/addExtendMagazine_RPK16';
import addExtendMagazine_AA12G1 from './modifies/addExtendMagazine_AA12G1';
import addExtendMagazine_AA12G2 from './modifies/addExtendMagazine_AA12G2';
import addExtendMagazine_KS23M from './modifies/addExtendMagazine_KS23M';
import addExtendMagazine_M3 from './modifies/addExtendMagazine_M3';
import addExtendMagazine_M590A1 from './modifies/addExtendMagazine_M590A1';
import addExtendMagazine_M870 from './modifies/addExtendMagazine_M870';
import addExtendMagazine_MP133 from './modifies/addExtendMagazine_MP133';
import addExtendMagazine_MP153 from './modifies/addExtendMagazine_MP153';
import addExtendMagazine_MP155 from './modifies/addExtendMagazine_MP155';
import addExtendMagazine_SAIGA12K from './modifies/addExtendMagazine_SAIGA12K';
import addExtendMagazine_SAIGA12KFA from './modifies/addExtendMagazine_SAIGA12KFA';
import addExtendMagazine_TOZ106 from './modifies/addExtendMagazine_TOZ106';
import addExtendMagazine_MP5 from './modifies/addExtendMagazine_MP5';
import addExtendMagazine_MP5K from './modifies/addExtendMagazine_MP5K';
import addExtendMagazine_MP7A1 from './modifies/addExtendMagazine_MP7A1';
import addExtendMagazine_MP7A2 from './modifies/addExtendMagazine_MP7A2';
import addExtendMagazine_MP9 from './modifies/addExtendMagazine_MP9';
import addExtendMagazine_MP9N from './modifies/addExtendMagazine_MP9N';
import addExtendMagazine_MPX from './modifies/addExtendMagazine_MPX';
import addExtendMagazine_P90 from './modifies/addExtendMagazine_P90';
import addExtendMagazine_PP9 from './modifies/addExtendMagazine_PP9';
import addExtendMagazine_PP1901 from './modifies/addExtendMagazine_PP1901';
import addExtendMagazine_PP91 from './modifies/addExtendMagazine_PP91';
import addExtendMagazine_PP9101 from './modifies/addExtendMagazine_PP9101';
import addExtendMagazine_PPSH41 from './modifies/addExtendMagazine_PPSH41';
import addExtendMagazine_SAIGA9 from './modifies/addExtendMagazine_SAIGA9';
import addExtendMagazine_SR2M from './modifies/addExtendMagazine_SR2M';
import addExtendMagazine_STM9 from './modifies/addExtendMagazine_STM9';
import addExtendMagazine_UMP45 from './modifies/addExtendMagazine_UMP45';
import addExtendMagazine_UZI from './modifies/addExtendMagazine_UZI';
import addExtendMagazine_UZIPP from './modifies/addExtendMagazine_UZIPP';
import addExtendMagazine_UZIPS from './modifies/addExtendMagazine_UZIPS';
import addExtendMagazine_Vector45 from './modifies/addExtendMagazine_Vector45';
import addExtendMagazine_Vector9 from './modifies/addExtendMagazine_Vector9';
import addExtendMagazine_APB from './modifies/addExtendMagazine_APB';
import addExtendMagazine_APS from './modifies/addExtendMagazine_APS';
import addExtendMagazine_ToyGun from './modifies/addExtendMagazine_ToyGun';
import addExtendMagazine_DE357 from './modifies/addExtendMagazine_DE357';
import addExtendMagazine_DE50L5 from './modifies/addExtendMagazine_DE50L5';
import addExtendMagazine_DE50L6 from './modifies/addExtendMagazine_DE50L6';
import addExtendMagazine_DE50L6WTS from './modifies/addExtendMagazine_DE50L6WTS';
import addExtendMagazine_DE50MKXIX from './modifies/addExtendMagazine_DE50MKXIX';
import addExtendMagazine_FN57 from './modifies/addExtendMagazine_FN57';
import addExtendMagazine_FN57F from './modifies/addExtendMagazine_FN57F';
import addExtendMagazine_Glock17 from './modifies/addExtendMagazine_Glock17';
import addExtendMagazine_Glock18C from './modifies/addExtendMagazine_Glock18C';
import addExtendMagazine_Glock19X from './modifies/addExtendMagazine_Glock19X';
import addExtendMagazine_M9A3 from './modifies/addExtendMagazine_M9A3';
import addExtendMagazine_M45A1 from './modifies/addExtendMagazine_M45A1';
import addExtendMagazine_M1911A1 from './modifies/addExtendMagazine_M1911A1';
import addExtendMagazine_MP443 from './modifies/addExtendMagazine_MP443';
import addExtendMagazine_P226R from './modifies/addExtendMagazine_P226R';
import addExtendMagazine_PB from './modifies/addExtendMagazine_PB';
import addExtendMagazine_PL15 from './modifies/addExtendMagazine_PL15';
import addExtendMagazine_PMT from './modifies/addExtendMagazine_PMT';
import addExtendMagazine_PM from './modifies/addExtendMagazine_PM';
import addExtendMagazine_SR1MP from './modifies/addExtendMagazine_SR1MP';
import addExtendMagazine_TT33 from './modifies/addExtendMagazine_TT33';
import addExtendMagazine_TT33G from './modifies/addExtendMagazine_TT33G';
import addExtendMagazine_USP45 from './modifies/addExtendMagazine_USP45';

// example：https://github.com/sp-tarkov/mod-examples

// mods order by https://escapefromtarkov.fandom.com/wiki/Weapons

class Mod implements IPreSptLoadMod,IPostDBLoadMod,IPostSptLoadMod {
  private logger: ILogger;
  private databaseServer: DatabaseServer;
  private itemHelper: ItemHelper;
  private customItemService: CustomItemService;

  public preSptLoad(container: DependencyContainer): void {
    this.logger = container.resolve<ILogger>('WinstonLogger');
    this.databaseServer = container.resolve<DatabaseServer>('DatabaseServer');
    this.itemHelper = container.resolve<ItemHelper>('ItemHelper');
    this.customItemService = container.resolve<CustomItemService>('CustomItemService');
  }

  public postDBLoad(container: DependencyContainer): void {
    const tables: IDatabaseTables = this.databaseServer.getTables();

    addExtendMagazine_9A91(this.logger,this.customItemService,tables);
    addExtendMagazine_ADAR(this.logger,this.customItemService,tables);
    addExtendMagazine_AVT40(this.logger,this.customItemService,tables);
    addExtendMagazine_OPSKS(this.logger,this.customItemService,tables);
    addExtendMagazine_RFB(this.logger,this.customItemService,tables);
    addExtendMagazine_SAGAK545(this.logger,this.customItemService,tables);
    addExtendMagazine_SAGAK545S(this.logger,this.customItemService,tables);
    addExtendMagazine_SKS(this.logger,this.customItemService,tables);
    addExtendMagazine_SR3M(this.logger,this.customItemService,tables);
    addExtendMagazine_SVT40(this.logger,this.customItemService,tables);
    addExtendMagazine_TX15(this.logger,this.customItemService,tables);
    addExtendMagazine_VPO101(this.logger,this.customItemService,tables);
    addExtendMagazine_VPO136(this.logger,this.customItemService,tables);
    addExtendMagazine_VPO209(this.logger,this.customItemService,tables);
    addExtendMagazine_VSK94(this.logger,this.customItemService,tables);
    addExtendMagazine_AK12(this.logger,this.customItemService,tables);
    addExtendMagazine_AK74(this.logger,this.customItemService,tables);
    addExtendMagazine_AK74M(this.logger,this.customItemService,tables);
    addExtendMagazine_AK74N(this.logger,this.customItemService,tables);
    addExtendMagazine_AK101(this.logger,this.customItemService,tables);
    addExtendMagazine_AK102(this.logger,this.customItemService,tables);
    addExtendMagazine_AK103(this.logger,this.customItemService,tables);
    addExtendMagazine_AK104(this.logger,this.customItemService,tables);
    addExtendMagazine_AK105(this.logger,this.customItemService,tables);
    addExtendMagazine_AKM(this.logger,this.customItemService,tables);
    addExtendMagazine_AKMN(this.logger,this.customItemService,tables);
    addExtendMagazine_AKMS(this.logger,this.customItemService,tables);
    addExtendMagazine_AKMSN(this.logger,this.customItemService,tables);
    addExtendMagazine_AKS74(this.logger,this.customItemService,tables);
    addExtendMagazine_AKS74N(this.logger,this.customItemService,tables);
    addExtendMagazine_AKS74U(this.logger,this.customItemService,tables);
    addExtendMagazine_AKS74UB(this.logger,this.customItemService,tables);
    addExtendMagazine_AKS74UN(this.logger,this.customItemService,tables);
    addExtendMagazine_ASVAL(this.logger,this.customItemService,tables);
    addExtendMagazine_ASH12(this.logger,this.customItemService,tables);
    addExtendMagazine_AUGA1(this.logger,this.customItemService,tables);
    addExtendMagazine_AUGA3(this.logger,this.customItemService,tables);
    addExtendMagazine_AUGA3B(this.logger,this.customItemService,tables);
    addExtendMagazine_MDR556(this.logger,this.customItemService,tables);
    addExtendMagazine_MDR762(this.logger,this.customItemService,tables);
    addExtendMagazine_G36(this.logger,this.customItemService,tables);
    addExtendMagazine_416A5(this.logger,this.customItemService,tables);
    addExtendMagazine_M4A1(this.logger,this.customItemService,tables);
    addExtendMagazine_MCX(this.logger,this.customItemService,tables);
    addExtendMagazine_MCXSPEAR(this.logger,this.customItemService,tables);
    addExtendMagazine_MK47(this.logger,this.customItemService,tables);
    addExtendMagazine_RD704(this.logger,this.customItemService,tables);
    addExtendMagazine_SA58(this.logger,this.customItemService,tables);
    addExtendMagazine_SCARH(this.logger,this.customItemService,tables);
    addExtendMagazine_SCARHF(this.logger,this.customItemService,tables);
    addExtendMagazine_SCARL(this.logger,this.customItemService,tables);
    addExtendMagazine_SCARLF(this.logger,this.customItemService,tables);
    addExtendMagazine_Velociraptor(this.logger,this.customItemService,tables);
    addExtendMagazine_AXMC(this.logger,this.customItemService,tables);
    addExtendMagazine_DVL10(this.logger,this.customItemService,tables);
    addExtendMagazine_M700(this.logger,this.customItemService,tables);
    addExtendMagazine_MosinSniper(this.logger,this.customItemService,tables);
    addExtendMagazine_MosinInfantry(this.logger,this.customItemService,tables);
    addExtendMagazine_SV98(this.logger,this.customItemService,tables);
    addExtendMagazine_T5000M(this.logger,this.customItemService,tables);
    addExtendMagazine_TRGM10(this.logger,this.customItemService,tables);
    addExtendMagazine_VPO215(this.logger,this.customItemService,tables);
    addExtendMagazine_AK50(this.logger,this.customItemService,tables);
    addExtendMagazine_G28(this.logger,this.customItemService,tables);
    addExtendMagazine_M1A(this.logger,this.customItemService,tables);
    addExtendMagazine_MK18(this.logger,this.customItemService,tables);
    addExtendMagazine_RSASS(this.logger,this.customItemService,tables);
    addExtendMagazine_SR25(this.logger,this.customItemService,tables);
    addExtendMagazine_SVDS(this.logger,this.customItemService,tables);
    addExtendMagazine_VSS(this.logger,this.customItemService,tables);
    addExtendMagazine_M60E4(this.logger,this.customItemService,tables);
    addExtendMagazine_M60E6(this.logger,this.customItemService,tables);
    addExtendMagazine_M60E6F(this.logger,this.customItemService,tables);
    addExtendMagazine_PKM(this.logger,this.customItemService,tables);
    addExtendMagazine_PKP(this.logger,this.customItemService,tables);
    addExtendMagazine_RPD(this.logger,this.customItemService,tables);
    addExtendMagazine_RPDN(this.logger,this.customItemService,tables);
    addExtendMagazine_RPK16(this.logger,this.customItemService,tables);
    //
    addExtendMagazine_AA12G1(this.logger,this.customItemService,tables);
    addExtendMagazine_AA12G2(this.logger,this.customItemService,tables);
    addExtendMagazine_KS23M(this.logger,this.customItemService,tables);
    addExtendMagazine_M3(this.logger,this.customItemService,tables);
    addExtendMagazine_M590A1(this.logger,this.customItemService,tables);
    addExtendMagazine_M870(this.logger,this.customItemService,tables);
    addExtendMagazine_MP133(this.logger,this.customItemService,tables);
    addExtendMagazine_MP153(this.logger,this.customItemService,tables);
    addExtendMagazine_MP155(this.logger,this.customItemService,tables);
    addExtendMagazine_SAIGA12K(this.logger,this.customItemService,tables);
    addExtendMagazine_SAIGA12KFA(this.logger,this.customItemService,tables);
    addExtendMagazine_TOZ106(this.logger,this.customItemService,tables);
    //
    addExtendMagazine_MP5(this.logger,this.customItemService,tables);
    addExtendMagazine_MP5K(this.logger,this.customItemService,tables);
    addExtendMagazine_MP7A1(this.logger,this.customItemService,tables);
    addExtendMagazine_MP7A2(this.logger,this.customItemService,tables);
    addExtendMagazine_MP9(this.logger,this.customItemService,tables);
    addExtendMagazine_MP9N(this.logger,this.customItemService,tables);
    addExtendMagazine_MPX(this.logger,this.customItemService,tables);
    addExtendMagazine_P90(this.logger,this.customItemService,tables);
    addExtendMagazine_PP9(this.logger,this.customItemService,tables);
    addExtendMagazine_PP1901(this.logger,this.customItemService,tables);
    addExtendMagazine_PP91(this.logger,this.customItemService,tables);
    addExtendMagazine_PP9101(this.logger,this.customItemService,tables);
    addExtendMagazine_PPSH41(this.logger,this.customItemService,tables);
    addExtendMagazine_SAIGA9(this.logger,this.customItemService,tables);
    addExtendMagazine_SR2M(this.logger,this.customItemService,tables);
    addExtendMagazine_STM9(this.logger,this.customItemService,tables);
    addExtendMagazine_UMP45(this.logger,this.customItemService,tables);
    addExtendMagazine_UZI(this.logger,this.customItemService,tables);
    addExtendMagazine_UZIPP(this.logger,this.customItemService,tables);
    addExtendMagazine_UZIPS(this.logger,this.customItemService,tables);
    addExtendMagazine_Vector45(this.logger,this.customItemService,tables);
    addExtendMagazine_Vector9(this.logger,this.customItemService,tables);
    addExtendMagazine_APB(this.logger,this.customItemService,tables);
    addExtendMagazine_APS(this.logger,this.customItemService,tables);
    addExtendMagazine_ToyGun(this.logger,this.customItemService,tables);
    addExtendMagazine_DE357(this.logger,this.customItemService,tables);
    addExtendMagazine_DE50L5(this.logger,this.customItemService,tables);
    addExtendMagazine_DE50L6(this.logger,this.customItemService,tables);
    addExtendMagazine_DE50L6WTS(this.logger,this.customItemService,tables);
    addExtendMagazine_DE50MKXIX(this.logger,this.customItemService,tables);
    addExtendMagazine_FN57(this.logger,this.customItemService,tables);
    addExtendMagazine_FN57F(this.logger,this.customItemService,tables);
    addExtendMagazine_Glock17(this.logger,this.customItemService,tables);
    addExtendMagazine_Glock18C(this.logger,this.customItemService,tables);
    addExtendMagazine_Glock19X(this.logger,this.customItemService,tables);
    addExtendMagazine_M9A3(this.logger,this.customItemService,tables);
    addExtendMagazine_M45A1(this.logger,this.customItemService,tables);
    addExtendMagazine_M1911A1(this.logger,this.customItemService,tables);
    addExtendMagazine_MP443(this.logger,this.customItemService,tables);
    addExtendMagazine_P226R(this.logger,this.customItemService,tables);
    addExtendMagazine_PB(this.logger,this.customItemService,tables);
    addExtendMagazine_PL15(this.logger,this.customItemService,tables);
    addExtendMagazine_PMT(this.logger,this.customItemService,tables);
    addExtendMagazine_PM(this.logger,this.customItemService,tables);
    addExtendMagazine_SR1MP(this.logger,this.customItemService,tables);
    addExtendMagazine_TT33(this.logger,this.customItemService,tables);
    addExtendMagazine_TT33G(this.logger,this.customItemService,tables);
    addExtendMagazine_USP45(this.logger,this.customItemService,tables);

    //
    this.logger.success('[SPTarkovExtendMagazine]: done');
  }

  public postSptLoad(container: DependencyContainer): void {
    //
  }
}

export const mod = new Mod();
